BIO-210: Applied software engineering for life sciences
# Python Introduction III - Numpy 2 and branching operations

## A deeper dive into Numpy
**Numpy** is a widely used Python library for scientific computing. During the last lesson you already learnt quite a few features of **Numpy**. Today, let's explore more features!

In [24]:
import numpy as np

### Slicing operations (refresh)

Let's review together how to index a multi-dimensional array using slicing

In [25]:
a = np.arange(1,101).reshape(10,10)

print('By default, indexing with colon will return all rows and columns')
b = a[:,:]  #[all rows, all columns]
print(b)

print('We can define the start at the end of indexed rows')
b = a[1:3,:]  #[all rows, all columns]
print(b)

print('or the start at the end of indexed columns')
b = a[:,1:3]  #[all rows, all columns]
print(b)

print('We can also specify the start and the end for both rows and columns')
b = a[4:7,1:3]  #[all rows, all columns]
print(b)

By default, indexing with colon will return all rows and columns
[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]
We can define the start at the end of indexed rows
[[11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]]
or the start at the end of indexed columns
[[ 2  3]
 [12 13]
 [22 23]
 [32 33]
 [42 43]
 [52 53]
 [62 63]
 [72 73]
 [82 83]
 [92 93]]
We can also specify the start and the end for both rows and columns
[[42 43]
 [52 53]
 [62 63]]


Sometimes, it can be useful to skip indexes. This can be achieved by adding another colon (`:`) and the value that specify how many values you want to skip. Therefore, we can summarize all slicing operations with the following notation `[start_idx : end_idx : skip_idx]`.

In [26]:
print('Print every fourth rows')
b = a[::4,:]
print(b)

Print every fourth rows
[[ 1  2  3  4  5  6  7  8  9 10]
 [41 42 43 44 45 46 47 48 49 50]
 [81 82 83 84 85 86 87 88 89 90]]


While here we are working with relatively small arrays, in real life you might work with large datasets having several axes. When that's the case, the ellipsis syntax (`...`) is useful to skip multiple axes. For example, imagine we have a 5D array and we want to get all the axes except the last one, where we want to get the first two elements. We can use the following syntax:

In [27]:
a = np.random.randn(4,4,4,4,4)
print(a)
print('a.shape:', a.shape)
a_sub = a[..., :2] # equivalent to a[:,:,:,:,:2]
print('a_sub.shape:', a_sub.shape)

[[[[[-0.73259046  1.65545975  1.08024118 -0.42085442]
    [-1.6054865   1.72937103  1.54958104 -0.65992926]
    [ 1.6515223  -0.91994808 -0.82500721 -0.33333335]
    [-2.40580452  0.41883391  0.65998413 -0.8733521 ]]

   [[ 1.24488699 -0.13564178 -0.59178281 -0.5337302 ]
    [-1.6150049  -1.10536026 -0.78325083 -0.47528696]
    [ 0.77357331 -1.32467894 -1.18685341 -0.80151691]
    [-0.94098032 -1.80859046 -0.79334853  0.26840461]]

   [[-0.49428918  0.52879157  2.74870648  0.5111648 ]
    [-2.84354461  1.27828775 -0.62351866 -1.01917844]
    [ 0.18338327 -0.17158633  1.24856519 -0.10013884]
    [ 0.89725172  0.7664134   1.15609714  0.74210532]]

   [[-0.48173285 -0.77885719  1.21689275  0.23953797]
    [-1.26093379 -1.37300118 -0.33930374 -1.55224907]
    [ 0.01330765 -0.50545944 -0.59965776  0.15699968]
    [ 1.38298739  1.42096562  0.82907462 -0.63712526]]]


  [[[ 0.44825886  0.22312607 -0.23625828 -0.2219254 ]
    [ 0.23240939  0.11068342 -0.74111152 -0.07567086]
    [-0.86750453  

**Exercise 0.** Index matrix <code>a</code> and print all even numbers between 40 (excluded) and 70.

In [28]:
b = a[4:7,1::2]  #[all rows, all columns]
print(b)

[]


### Basic statistical functions
NumPy contains various statistical functions that are used for data analysis. These functions are useful, for example, to find the maximum or the minimum element of a vector. It is also used to compute common statistical operations like standard deviation, variance, etc.

The functions <code>mean</code> and <code>std</code> are used to caculate the mean and standard deviation of the input data (e.g., of an array). Besides caculating the result for the whole data, they can also be used to calculate it along a specific axis.

In [29]:
a = np.array([[1, 2], [3, 4]])

print("The full matrix:\n", a)
print("The mean of the whole matrix is:", np.mean(a))
print("The standard deviation of the whole matrix is:", np.std(a))
print("The mean of each column is:", np.mean(a, axis=0))
print("The mean of each row is:", np.mean(a, axis=1))
print("The standard deviation of each column is:", np.std(a, axis=0))

The full matrix:
 [[1 2]
 [3 4]]
The mean of the whole matrix is: 2.5
The standard deviation of the whole matrix is: 1.118033988749895
The mean of each column is: [2. 3.]
The mean of each row is: [1.5 3.5]
The standard deviation of each column is: [1. 1.]


Now, let's generate a random array drawn from a gaussian distribution $\mathcal{N}\left(3, 6.25\right)$. The **Numpy** function <code>random.randn</code> samples values from a standard gaussian distribution $\mathcal{N}\left(0, 1\right)$. Therefore, to get a gaussian distribution distribution $\mathcal{N}\left(3, 6.25\right)$, we need to multiply the vector by the standard deviation (i.e., $\sqrt{6.25}$) and by adding the mean (i.e., $3$).

In [30]:
a = 3 + 2.5 * np.random.randn(2, 4)

**Exercise 1.** Calculate the mean and standard deviation first of the whole matrix <code>a</code> and then along the first axis of matrix <code>a</code>.

In [31]:
print(np.mean(a))
print(np.std(a))
print(np.mean(a, axis=0))
print(np.std(a, axis=0))

3.064807678395922
1.7832098983100468
[2.13287193 4.17379435 2.6700895  3.28247493]
[0.44933934 0.66132021 0.98292674 2.96857167]


Is it close to what you expect? How would you create another matrix <code>a</code>, in which the mean and the standard deviation are closer to the expected ones? 

In [32]:
a = 3 + 2.5 * np.random.randn(100, 100)
print(np.mean(a))
print(np.std(a))
print(np.mean(a, axis=0))
print(np.std(a, axis=0))

2.9904579566166567
2.5072731201850615
[3.10541875 2.49603685 2.91885578 3.33744535 3.2932903  2.90978897
 2.67220505 2.78440997 2.86235316 3.22165684 2.41504156 2.70757555
 3.35381106 3.10099544 2.55861295 3.01582228 2.91416112 3.01357986
 3.10593719 2.98477492 3.07971777 3.55893887 3.29258474 3.12801052
 2.89650106 3.03472116 3.02446446 2.30289049 2.98279343 3.14805667
 2.58144433 3.07794682 3.14388897 3.07571043 2.76484406 2.94509178
 3.03467247 3.0301527  2.80982711 2.7456566  2.56985151 3.38005056
 2.6727635  3.01561375 2.90215531 3.46032185 2.97004436 3.2630465
 2.73746091 3.27658269 3.33390036 2.89638696 3.51980733 2.71361656
 2.81537787 3.19019628 3.02086331 2.80267468 3.45409111 3.14725347
 2.97773914 2.90822528 3.59174743 2.80860135 3.15160842 3.17729413
 3.323342   2.74538924 2.91385382 2.85295356 2.98961219 3.11351895
 2.85689969 2.29009684 2.44987694 2.82805582 3.20735298 2.78372852
 2.98537614 2.98109643 2.9340485  3.08334186 2.80671126 2.84375314
 3.3683201  2.93189283 2.

**Exercise 2.** Besides <code>mean</code> and <code>std</code>, **Numpy** also offers the functions <code>min</code>, <code>max</code>, <code>median</code>, <code>argmin</code>, <code>argmax</code> to caculate the minimum, maximum and median values, index of the minimum and index of the maximum of the array. Apply these functions to the matrix <code>a</code> and along its axis 0 (think of it as coordinates of your array, with axis 0 along rows and axis 1 along columns). Take a better look at the example above to help you understand the importance of this parameter! If you still feel confused check out [this article](https://www.sharpsightlabs.com/blog/numpy-axes-explained/#numpy-axes-quick-explanation).

In [33]:
print(np.min(a))
print(np.max(a))
print(np.median(a))
print(np.argmin(a))
print(np.argmax(a))
print(np.min(a, axis=0))
print(np.max(a, axis=0))
print(np.median(a, axis=0))
print(np.argmin(a, axis=0))
print(np.argmax(a, axis=0))

-6.979279296567148
12.032330825220777
2.9771355543544926
4035
3841
[-3.12832309 -5.31194792 -2.8816978  -2.72265791 -2.37058577 -2.7162038
 -2.7007688  -3.75540962 -1.48343833 -3.51255916 -3.63385632 -5.53817595
 -2.9676817  -4.31863239 -5.35568812 -3.76613221 -2.28588299 -2.46622853
 -2.40289339 -3.13675217 -5.03052703 -1.39053094 -1.91904117 -3.79454246
 -3.21374104 -2.7022795  -1.68386541 -3.01199193 -2.10728892 -2.0145649
 -3.56639044 -2.65559535 -3.27633916 -3.29520907 -3.31410924 -6.9792793
 -4.5583797  -2.84875665 -3.85645354 -2.34909069 -4.58729219 -2.78805561
 -2.14821199 -3.01051143 -6.52258767 -2.93503089 -4.28876851 -4.24326889
 -4.29138525 -5.63549462 -2.54672068 -3.50023718 -3.14840135 -2.88378325
 -2.3918024  -3.03145261 -5.14022247 -3.85196265 -2.42263187 -1.917807
 -2.47422481 -3.21945669 -3.69215113 -2.16874898 -1.68640033 -1.42160212
 -1.96567707 -3.20291171 -3.45131056 -1.94554154 -3.02927807 -2.431723
 -2.48302331 -4.36795739 -4.48227289 -5.32018809 -5.07392065 -3.

**Numpy** also supports non-standard numbers, such as **np.inf**, which represents infinity, and **np.nan**, which represents "not-a-number". These can be the results of operations such as division by 0:

In [34]:
a = np.array([0, 1, -4]) / 0
print("Dividing by 0 can generate np.nan or np.inf (also negative) as a result:", a)

Dividing by 0 can generate np.nan or np.inf (also negative) as a result: [ nan  inf -inf]


/var/folders/kf/0ks7zrps72scr4cj79sdx08m0000gq/T/ipykernel_69182/972857553.py:1: RuntimeWarning: divide by zero encountered in true_divide
  a = np.array([0, 1, -4]) / 0
/var/folders/kf/0ks7zrps72scr4cj79sdx08m0000gq/T/ipykernel_69182/972857553.py:1: RuntimeWarning: invalid value encountered in true_divide
  a = np.array([0, 1, -4]) / 0


Standard operations, when applied to data containing np.nan, will also return **np.nan**:

In [35]:
a = [0, np.nan, 1]
print("The mean of a vector with a NaN is: ", np.mean(a))

The mean of a vector with a NaN is:  nan


However, **Numpy** offers functions that can ignore NaNs, such as <code>nanmax</code>, <code>nanmin</code> and <code>nanmean</code> . Let's create an array including NaN values and test these functions.

**Exercise 3.** Apply the following functions of numpy to the array a: <code>min</code>, <code>max</code> and <code>nanmin</code>, <code>nanmax</code>.

In [36]:
a = np.array([1, 2, np.nan, np.inf])
print(np.min(a))
print(np.max(a))
print(np.nanmin(a))
print(np.nanmax(a))

nan
nan
1.0
inf


**Exercise 4.** We want to write some code which, given a point, finds the closest one in a set of other points. Such a function is important, for example, in information theory, as it is the basic operation of the vector quantization (VQ) algorithm. In the simple, two-dimensional case shown below, the values refer to the weight and height of an athlete. The set of weights and heights represents different classes of athletes. We want to assign the athlete to the class it is closest to. Finding the closest point requires calculating the Euclidean distance between the athlete's parameters and each of the classes of athletes.
Now, let's define an athlete with 
$$\left[\text{weight, height}\right] = \left[111.0, 188.0\right]$$
and an array of 4 classes
$$[[102.0, 203.0],$$
$$[132.0, 193.0],$$
$$[45.0, 155.0],$$
$$[57.0, 173.0]]$$
In the next cell, write some code which returns the index of the class of athletes that the athlete should be assigned to.

In [37]:
observation = np.array([111.0, 188.0])
codes = np.array([[102.0, 203.0],
               [132.0, 193.0],
               [45.0, 155.0],
               [57.0, 173.0]])
diff = codes - observation    # the broadcast happens here
print(diff.shape)
dist = np.sqrt(np.sum(diff**2, axis=-1))
print(np.argmin(dist))

(4, 2)
0


### Linear algebra examples
Linear algebra is at the core of Data Science. That's why **NumPy** offers array-like data structures & dedicated operations and methods. Let's first have a look together at the <code>dot</code> function as an example, which computes the matrix multiplication between two vectors or matrices.

In [38]:
a = np.array([[1,2,3],[2,0,3],[7,-5,1]])
b = np.array([[3,-1,5],[-2,-6,4], [0,4,4]])
print('a @ b: \n', np.dot(a,b))
print('a @ b: \n', a.dot(b))

a @ b: 
 [[-1 -1 25]
 [ 6 10 22]
 [31 27 19]]
a @ b: 
 [[-1 -1 25]
 [ 6 10 22]
 [31 27 19]]


**Exercise 5.** Define two random matrices, `a` and `b`, of sizes (4x2). Transpose `b` and save in `c` the matrix product between `a` and `b` transposed.

In [39]:
a = np.random.randn(4, 2)
b = np.random.randn(4, 2)
b = np.transpose(b)
c = np.dot(a, b)

**Exercise 6.** Can the `c` matrix be inverted? Check it out by computing its determinant and, if it exists, get the inverse matrix.

In [40]:
if np.abs(np.linalg.det(c)) > 1e-6:
    inv_c = np.linalg.inv(c)
    print(inv_c)
else: 
    print("The determinant is too small")

The determinant is too small


**Exercise 7.** Using the inverse matrix and the matrix-multiplication operator, you can now solve a matrix-vector equation. Let's now find the vector $x$ that solves the equation
$$Ax = b$$
given $A=\left(\begin{matrix} 2 & 1 & -2\\ 3 & 0 & 1\\ 1 & 1 & -1\end{matrix}\right)$ and $b=\left(\begin{matrix}-3 \\ 5 \\ -2 \end{matrix}\right)$.

In [41]:
A = np.array([[2,1,-2],[3,0,1],[1,1,-1]])
A_inv = np.linalg.inv(A)
b = np.transpose(np.array([[-3,5,-2]]))
print(f"The shape of A is {A.shape}")
print(f"The shape of A_inv is {A_inv.shape}")
print(f"The shape of b is {b.shape}")
x = np.dot(A_inv, b)
print("The solution is:\n", x)

The shape of A is (3, 3)
The shape of A_inv is (3, 3)
The shape of b is (3, 1)
The solution is:
 [[ 1.]
 [-1.]
 [ 2.]]


**Exercise 8.** Computing the inverse could be very time-consuming. Therefore, it is always better to take advantage of the highly optimized **NumPy** functions to solve linear equations. Try to solve the same exercise as before but using **NumPy**'s function <code>linalg.solve</code> to compute $x$.

In [42]:
x = np.linalg.solve(A,b)
print(x)

[[ 1.]
 [-1.]
 [ 2.]]


## Branching operations

### *if*, *else* and *elif*
In Python, similarly to all of the C-like languages, branching operations are implemented using the **if** keyword. If the expression is true, the statement following it will be executed. Otherwise, it is possible to specify the statement to execute in case of the expression is false, by using the *else* keyword. Both **if** and **else** need a colon (`:`) at the line, as in the following example:

In [43]:
r = np.random.randn()
if r > 0:
    print("The random number is positive")
else:
    print("The random number is negative")

The random number is negative


In case you want to create multiple branches by applying more than one condition, you can use the keyword **elif** as in the following example:

In [44]:
animal = "cat"

if animal == "cat":
    print("meow")
elif animal == "dog":
    print("woof")
elif animal == "cow":
    print("moo")
else:
    print(f"I don't know  the {animal}'s call, sorry :(")

meow


**Exercise 9.** Let's try to implement a calculator using **if**, **else** and **elif**. The head of the calculator is already written as the following. You can input `a`, `b` and `option` when running the code. There should be 4 allowed operations:
- addition (`1`)
- subtraction (`2`)
- multiplication (`3`)
- division (`4`)

If the option is not one of the 4, the calculator should print "Invalid option". Implement the missing code using the `if`, `elif` and `else` statements along with the appropriate operations.

In [45]:
print("Welcome to CALCULATOR!")

a = float(input("Enter the first number: "))
b = float(input("Enter the second number: "))

print("Choose one of the following operations:")
print("1 - addition")
print("2 - subtraction")
print("3 - multiplication")
print("4 - division")

option = int(input(""))

if (option == 1):
    result = a + b
elif (option == 2):
    result = a - b
elif (option == 3):
    result = a * b
elif (option == 4):
    result = a / b
if option > 0 and option < 5:
    print("result: %f" % (result))
else:
    print("Invalid option")
    
print("The result is ", result)

Welcome to CALCULATOR!
Choose one of the following operations:
1 - addition
2 - subtraction
3 - multiplication
4 - division
result: 2.000000
The result is  2.0


### *break* and *continue*

The **break** statement in Python terminates the current loop and resumes execution at the next statement, just like the traditional *break* found in C. On the other hand, the **continue** statement skips all the remaining code in the current iteration of the loop and moves the control back to the top of the loop.

**Exercise 10.** Try to use a `for` loop and the `continue` statement to remove all the `"h"`s in the string `"hello, haha, python"`. The result should be stored in a new string.

In [46]:
str_1 = "hello, haha, python"
str_2 = ""
for letter in str_1:
    if letter == 'h':
        continue
    str_2 += letter
print(str_2)

ello, aa, pyton


**Exercise 11.** Try to use a `for` loop and the `break` statement to only keep the letters before `"p"` in the string `"hello, haha, python"`. The result should be stored in a new string.

In [47]:
str_1 =  "hello, haha, python"
str_2 = ""
for letter in str_1:
    if letter == 'p':
        break
    str_2 += letter
print(str_2)

hello, haha, 
