BIO-210: Applied software engineering for life sciences
# Python Introduction III - Numpy 2 and branching operations

## A deeper dive into Numpy
**Numpy** is a widely used Python library for scientific computing. During the last lesson you already learnt quite a few features of **Numpy**. Today, let's explore more features!

In [1]:
import numpy as np

### Slicing operations (refresh)

Let's review together how to index a multi-dimensional array using slicing

In [2]:
a = np.arange(1,101).reshape(10,10)

print('By default, indexing with colon will return all rows and columns')
b = a[:,:]  #[all rows, all columns]
print(b)

print('We can define the start at the end of indexed rows')
b = a[1:3,:]  #[all rows, all columns]
print(b)

print('or the start at the end of indexed columns')
b = a[:,1:3]  #[all rows, all columns]
print(b)

print('We can also specify the start and the end for both rows and columns')
b = a[4:7,1:3]  #[all rows, all columns]
print(b)

By default, indexing with colon will return all rows and columns
[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]
We can define the start at the end of indexed rows
[[11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]]
or the start at the end of indexed columns
[[ 2  3]
 [12 13]
 [22 23]
 [32 33]
 [42 43]
 [52 53]
 [62 63]
 [72 73]
 [82 83]
 [92 93]]
We can also specify the start and the end for both rows and columns
[[42 43]
 [52 53]
 [62 63]]


Sometimes, it can be useful to skip indexes. This can be achieved by adding another colon (:) and the value that specify how many values you want to skip. Therefore, we can summarize all slicing operations with the following notation [start_idx : end_idx : skip_idx].

In [3]:
print('Print every fourth rows')
b = a[::4,:]
print(b)

Print every fourth rows
[[ 1  2  3  4  5  6  7  8  9 10]
 [41 42 43 44 45 46 47 48 49 50]
 [81 82 83 84 85 86 87 88 89 90]]


**Exercise 0** Index matrix <code>a</code> and print all even numbers between 40 (excluded) and 70.

In [4]:
b = a[4:7,1::2]  #[all rows, all columns]
print(b)

[[42 44 46 48 50]
 [52 54 56 58 60]
 [62 64 66 68 70]]


### Basic statistical functions
NumPy contains various statistical functions that are used for data analysis. These functions are useful, for example, to find the maximum or the minimum element of a vector. It is also used to compute common statistical operations like standard deviation, variance, etc.

The functions <code>mean</code> and <code>std</code> are used to caculate the mean and standard deviation of the input data (e.g., of an array). Besides caculating the result for the whole data, they can also be used to caculate it along a specific axis.

In [5]:
a = np.array([[1, 2], [3, 4]])

print("The full matrix:\n", a)
print("The mean of the whole matrix is:", np.mean(a))
print("The standard deviation of the whole matrix is:", np.std(a))
print("The mean of each column is:", np.mean(a, axis=0))
print("The mean of each row is:", np.mean(a, axis=1))
print("The standard deviation of each column is:", np.std(a, axis=0))

The full matrix:
 [[1 2]
 [3 4]]
The mean of the whole matrix is: 2.5
The standard deviation of the whole matrix is: 1.118033988749895
The mean of each column is: [2. 3.]
The mean of each row is: [1.5 3.5]
The standard deviation of each column is: [1. 1.]


Now, let's generate a random array drawn from a gaussian distribution N(3, 6.25). The function <code>random.randn</code> samples values from a standard gaussian distribution N(0, 1). Therefore, to get a gaussian distribution distribution N(3, 6.25), we need to multiply the vector by the standard deviation (i.e., sqrt(6.25)) and by adding the mean (i.e., 3).

In [6]:
a = 3 + 2.5 * np.random.randn(2, 4)

**Exercise 1.** Calculate the mean and standard deviation first of the whole matrix <code>a</code> and then along the first axis of matrix <code>a</code>.

In [7]:
print(np.mean(a))
print(np.std(a))
print(np.mean(a, axis=0))
print(np.std(a, axis=0))

3.3400938885194584
3.335112472892346
[3.03192444 2.22066263 0.5542242  7.55356429]
[2.83010726 0.60004796 0.61868164 2.97944151]


Is it close to what you expect? How would you create another matrix <code>a</code>, in which the mean and the standard deviation are closer to the expected ones? 

In [8]:
a = 3 + 2.5 * np.random.randn(100, 100)
print(np.mean(a))
print(np.std(a))
print(np.mean(a, axis=0))
print(np.std(a, axis=0))

2.9972010557293767
2.526760827735842
[2.93977012 2.67531536 2.64582574 3.0366958  2.80564266 2.96795986
 3.23718672 3.35431732 3.09617258 3.3013108  3.01359204 2.89913368
 3.10376674 3.20444616 2.84747505 3.0568911  3.20573066 3.64646284
 2.88786644 2.9405187  3.05102207 2.8862812  2.78374621 3.22978878
 2.8786577  3.44023758 3.09315937 2.99595657 2.72162686 2.8824967
 3.06304732 2.83305737 3.32156959 2.82123933 3.10193946 3.34228334
 3.03916623 3.194378   2.99524997 3.28241791 3.35925161 2.9336327
 3.26252065 2.70419027 3.04390184 2.82071582 3.11548466 3.05862928
 3.16383861 3.11822985 2.97376327 2.98662305 3.06257487 3.10307016
 2.84663759 3.29832327 2.71905212 2.75860917 3.16968533 2.6019555
 3.02340248 2.85785546 2.5696728  2.59577458 2.70063319 2.9484885
 2.84804535 2.38976831 3.18401271 3.27267841 3.08745655 2.97265724
 3.22999134 3.15421163 3.09805708 3.26255257 2.94122329 2.62946888
 2.97017555 2.81752911 2.96726081 3.0767243  3.11521174 2.85332985
 2.79560272 2.97269301 3.2287

**Exercise 2.** Besides <code>mean</code> and <code>std</code>, **Numpy** also offers the functions <code>min</code>, <code>max</code>, <code>median</code>, <code>argmin</code>, <code>argmax</code> to caculate the minimum, maximum and median values, index of the minimum and index of the maximum of the array. Apply these functions to the matrix <code>a</code> and along its axis 0 (think of it as coordinates of your array, with axis 0 along rows and axis 1 along columns). Take a better look at the example above to help you understand the importance of this parameter! If you still feel confused check out [this article](https://www.sharpsightlabs.com/blog/numpy-axes-explained/#numpy-axes-quick-explanation).

In [9]:
print(np.amin(a))
print(np.amax(a))
print(np.median(a))
print(np.argmin(a))
print(np.argmax(a))
print(np.amin(a, axis=0))
print(np.amax(a, axis=0))
print(np.median(a, axis=0))
print(np.argmin(a, axis=0))
print(np.argmax(a, axis=0))

-5.864795313400949
12.364914203830594
3.0175172918937094
4583
2354
[-3.15408098 -1.72691558 -2.29687686 -4.2244136  -4.73764389 -3.2363633
 -2.39687128 -3.98986089 -1.45994102 -3.42805819 -3.69126849 -4.2198638
 -3.98633382 -3.43241219 -3.99090511 -2.17948676 -2.81650535 -1.5773979
 -3.70162141 -4.6714328  -3.35679637 -2.58016899 -4.36868427 -3.5236138
 -4.90536247 -2.85404656 -2.48565354 -4.15259483 -2.98869827 -2.84447676
 -2.15119991 -2.62977778 -2.1864563  -4.27089249 -5.43869544 -2.81083286
 -1.77298241 -2.39733863 -3.31967885 -1.18588553 -2.33370516 -4.17279934
 -3.1032587  -2.87695779 -3.49266109 -2.89227965 -2.86329037 -1.36788807
 -3.33351963 -3.64248158 -1.25286169 -3.11552787 -4.02170759 -4.0232822
 -3.69497435 -3.93015674 -3.30943856 -5.34103763 -2.98793991 -4.25078621
 -2.71623253 -5.85529783 -3.45545932 -2.66994509 -2.52944365 -4.16014274
 -3.40742845 -3.94953284 -2.43652005 -4.63554588 -3.50498084 -3.44392145
 -2.21960712 -4.30925236 -4.36186185 -4.29919144 -3.66956669 -

**Numpy** also supports non-standard numbers, such as **np.inf**, which represents infinity, and **np.nan**, which represents "not-a-number". These can be the results of operations such as division by 0:

In [11]:
a = np.array([0, 1, -4]) / 0
print("Dividing by 0 can generate np.nan or np.inf (also negative) as a result:", a)

Dividing by 0 can generate np.nan or np.inf (also negative) as a result: [ nan  inf -inf]


<ipython-input-11-1d7df589b35e>:1: RuntimeWarning: divide by zero encountered in true_divide
  a = np.array([0, 1, -4]) / 0
<ipython-input-11-1d7df589b35e>:1: RuntimeWarning: invalid value encountered in true_divide
  a = np.array([0, 1, -4]) / 0


Standard operations, when applied to data containing np.nan, will also return **np.nan**:

In [12]:
a = [0, np.nan, 1]
print("The mean of a vector with a NaN is: ", np.mean(a))

The mean of a vector with a NaN is:  nan


However, **Numpy** offers functions that can ignore NaNs, such as <code>nanmax</code>, <code>nanmin</code> and <code>nanmean</code> . Let's create an array including NaN values and test these functions.

**Exercise 3.** Apply the following functions of numpy to the array a: <code>amax</code>, <code>amin</code> and <code>nanmax</code>, <code>nanmin</code>.

In [13]:
a = np.array([1, 2, np.nan, np.inf])
print(np.amin(a))
print(np.amax(a))
print(np.nanmin(a))
print(np.nanmax(a))

nan
nan
1.0
inf


**Exercise 4.** We want to write some code which, given a point, finds the closest one in a set of other points. Such a function is important, for example, in information theory, as it is the basic operation of the vector quantization (VQ) algorithm. In the simple, two-dimensional case shown below, the values refer to the weight and height of an athlete. The set of weights and heights represents different classes of athletes. We want to assign the athlete to the class it is closest to. Finding the closest point requires calculating the distance between the athlete's parameters and each of the classes of athletes.
Now, let's define an athlete with [weight, height] = [111.0, 188.0], and a list of 4 classes [[102.0, 203.0], [132.0, 193.0], [45.0, 155.0], [57.0, 173.0]]. In the next cell, write some code which returns the index of the class of athletes that the athlete should be assigned to.

In [14]:
observation = np.array([111.0, 188.0])
codes = np.array([[102.0, 203.0],
               [132.0, 193.0],
               [45.0, 155.0],
               [57.0, 173.0]])
diff = codes - observation    # the broadcast happens here
print(diff.shape)
dist = np.sqrt(np.sum(diff**2, axis=-1))
print(np.argmin(dist))

(4, 2)
0


### Linear algebra examples
Linear algebra is at the core of Data Science. That's why **NumPy** offers array-like data structures & dedicated operations and methods. Let's first have a look together at the <code>dot</code> function as an example, which computes the matrix multiplication between two vectors or matrices.

In [15]:
a = np.array([[1,2,3],[2,0,3],[7,-5,1]])
b = np.array([[3,-1,5],[-2,-6,4], [0,4,4]])
print('a @ b: \n', np.dot(a,b))
print('a @ b: \n', a.dot(b))

a @ b: 
 [[-1 -1 25]
 [ 6 10 22]
 [31 27 19]]
a @ b: 
 [[-1 -1 25]
 [ 6 10 22]
 [31 27 19]]


**Exercise 5.** Define two random matrices, a and b, of sizes (4x2). Transpose b and save in c the matrix product between a and b transposed.

In [16]:
a = np.random.randn(4, 2)
b = np.random.randn(4, 2)
b = np.transpose(b)
c = np.matmul(a, b)

**Exercise 6.** Can the c matrix be inverted? Check it out by computing its determinant and, if it exists, get the inverse matrix.

In [17]:
if np.abs(np.linalg.det(c)) > 1e-6:
    inv_c = np.linalg.inv(c)
    print(inv_c)
else: 
    print("The determinant is too small")

 The determinant is too small 


**Exercise 7.** Using the inverse matrix and the matrix-multiplication operator, you can now solve a matrix-vector equation. Let's now find the vector x that solve the following equation Ax = b. Given A equal to ([2,1,-2],[3,0,1],[1,1,-1]]) and b equal to ([-3,5,-2]), compute x.

In [18]:
A = np.array([[2,1,-2],[3,0,1],[1,1,-1]])
b = np.transpose(np.array([[-3,5,-2]]))
print(b.shape)
x = np.matmul(np.linalg.inv(A), b)
print(x)

(3, 1)
[[ 1.]
 [-1.]
 [ 2.]]


**Exercise 8.** Computing the inverse could be very time-consuming. Therefore, it is always better to take advantage of the highly optimized **NumPy** functions to solve linear equations. Try to solve the same exercise as before but using <code>linalg.solve</code> to compute x.

In [38]:
x = np.linalg.solve(A,b)
print(x)

[[ 1.]
 [-1.]
 [ 2.]]


## Branching operation

### *if*, *else* and *elif*
In Python, similarly to all of the C-like languages, branching operations are implemented using the **if** keyword. If the expression is true, the statement following it will be executed. Otherwise, it is possible to specify the statement to execute in case of the expression is false, by using the *else* keyword. Both **if** and **else** need a colon (:) at the line, as in the following example:

In [19]:
r = np.random.randn()
if r > 0:
    print("The random number is positive")
else:
    print("The random number is negative")

The random number is negative


In case you want to create multiple branches by applying more than one condition, you can use the keyword **elif** as in the following example:

In [20]:
animal = "cat"

if animal == "cat":
    print("meow")
elif animal == "dog":
    print("woof")
elif animal == "cow":
    print("moo")
else:
    print(f"I don't know  the {animal}'s call, sorry :(")

meow


**Exercise 9.** Let's try to implement a calculator using **if**, **else** and **elif**. The head of the calculator is already written as the following. You can input a, b and option when running the code. Now please finish the calculation.

In [21]:
print("Welcome to CALCULATOR!")

a = float(input("Enter the first number: "))
b = float(input("Enter the second number: "))

print("Choose one of the following operations:")
print("1 - addition")
print("2 - subtraction")
print("3 - multiplication")
print("4 - division")

option = int(input(""))

if (option == 1):
    result = a + b
elif (option == 2):
    result = a - b
elif (option == 3):
    result = a * b
elif (option == 4):
    result = a / b
if option > 0 and option < 5:
    print("result: %f" % (result))
else:
    print("Invalid option")
    
print("The result is ", result)

Welcome to CALCULATOR!
Choose one of the following operations:
1 - addition
2 - subtraction
3 - multiplication
4 - division
result: 3.000000
The result is  3.0


### *break* and *continue*

The **break** statement in Python terminates the current loop and resumes execution at the next statement, just like the traditional *break* found in C. On the other hand, the **continue** statement skips all the remaining code in the current iteration of the loop and moves the control back to the top of the loop.

**Exercise 10.** Try to use for loop and continue to remove all the "h"s in the string "hello, haha, python".

In [22]:
str_1 =  "hello, haha, python"
str_2 = []
for letter in str_1:
    if letter == 'h':
        continue
    str_2.append(letter)
print(str_2)

['e', 'l', 'l', 'o', ',', ' ', 'a', 'a', ',', ' ', 'p', 'y', 't', 'o', 'n']


**Exercise 11.** Try to use for loop and break to only keep the letters before "p" in the string "hello, haha, python".

In [23]:
str_1 =  "hello, haha, python"
str_2 = []
for letter in str_1:
    if letter == 'p':
        break
    str_2.append(letter)
print(str_2)

['h', 'e', 'l', 'l', 'o', ',', ' ', 'h', 'a', 'h', 'a', ',', ' ']
